const confList = [
"Anonymous: Crush er id te fake id diye stalk kori",
"Anonymous: Exam er khata te doodle kori beshi",
"Anonymous: Class e ghumay sir er kache dhora khaisi",
"Anonymous: Bondhur khabar churi kore khai",
"Anonymous: Rat 3tay ex er profile dekhi",
"Anonymous: Assignment copy kore A+ paisi",
"Anonymous: Ma ke mittha bole bahire gesi",
"Anonymous: Online e nije ke rich dabi kori",
"Anonymous: Gym er membership niye jai na",
"Anonymous: Crush er samne pore jawa natok korsi",
"Anonymous: Teacher er name e nickname rakhsi",
"Anonymous: Exam er age ek rat o pori na",
"Anonymous: Crush er story 10 bar dekhi",
"Anonymous: Friend er charger churi kore niye asi",
"Anonymous: Online class e ghumai",
"Anonymous: Birthday te nijeke wish kori",
"Anonymous: Ex er jonno ekhono kanna kori",
"Anonymous: Crush er friend ke jiggesh kori o ki kore",
"Anonymous: Ma er mobile diye tiktok dekhi",
"Anonymous: Rat jege meme dekhi",
"Anonymous: Porashona na kore netflix dekhi",
"Anonymous: Crush er nam phone e onno name e save korsi",
"Anonymous: Group e 'ami busy' bole pubg kheli",
"Anonymous: Friend er secret onno jon ke bole disi",
"Anonymous: Online e 2 ta id chalai",
"Anonymous: Sir ashar age boi bondho kori",
"Anonymous: Crush ke dekhe heart beat bare",
"Anonymous: Bank balance 20tk kintu boli 20k",
"Anonymous: Photo te filter mere nijeke shundor banai",
"Anonymous: Ex ke stalk kore block khai",
"Anonymous: Assignment er jonno chatgpt use kori",
"Anonymous: Class e sir er pichone nokol kori",
"Anonymous: Crush er sathe kotha bolar bahana khuji",
"Anonymous: Rat 12tar por biriyani order dei",
"Anonymous: Ma ke boli pori, kintu youtube dekhi",
"Anonymous: Friend er gf er id te request disi",
"Anonymous: Exam e 'pass me sir' likhsi",
"Anonymous: Crush er post e first like dei",
"Anonymous: Online e nijeke influencer dabi kori",
"Anonymous: Gym e giye sudhu selfie tuli",
"Anonymous: Diet er nam e 3 bela biriyani khai",
"Anonymous: Crush er sathe dekha hole palai",
"Anonymous: Friend er password jani",
"Anonymous: Rat e ghum er age crush ke niye vabi",
"Anonymous: Online e kawke mittha boyosh bolsi",
"Anonymous: Class bunk kore adda dei",
"Anonymous: Crush er jonno gaan shuni",
"Anonymous: Ex er sathe abar kotha bolte chai",
"Anonymous: Friend er taka dhari niye ferot dei na",
"Anonymous: Online e kawke flirt korsi",
"Anonymous: Crush er sathe chat delete kore disi",
"Anonymous: Ma er kase lukay phone chalai",
"Anonymous: Exam er khata te sir ke request likhsi",
"Anonymous: Crush er puran pic save korsi",
"Anonymous: Rat e aka aka hashi",
"Anonymous: Friend ke jealous korar jonno mittha boli",
"Anonymous: Online e nije ke single dabi kori kintu crush ache",
"Anonymous: Class e note na likhe golpo likhi",
"Anonymous: Crush ke dekhe lojja pai",
"Anonymous: Ex er new gf ke stalk kori",
"Anonymous: Friend er birthday bhule gesi",
"Anonymous: Online e kawke propose korsi reject khaisi",
"Anonymous: Rat 4ta porjonto jege thaki",
"Anonymous: Crush er sathe kotha bolte voy pai",
"Anonymous: Friend er khabar e lobon beshi dei",
"Anonymous: Sir er samne valo student er natok kori",
"Anonymous: Online e fake news share kori",
"Anonymous: Crush er nam diye playlist banaisi",
"Anonymous: Exam er ager din natok dekhi",
"Anonymous: Friend ke 'tumi best' bole treat chai",
"Anonymous: Crush er sathe selfie tulte chai kintu pari na",
"Anonymous: Rat e aka kanna kori",
"Anonymous: Online e kawke block kore abar unblock kori",
"Anonymous: Ma ke mittha bole taka nei",
"Anonymous: Crush er sathe dream e dekha hoi",
"Anonymous: Friend er secret nijer kase rakhi na",
"Anonymous: Online e nijeke motivational speaker vabi",
"Anonymous: Crush ke 'bro' bole feli",
"Anonymous: Exam e nokol korte giye dhora khaisi",
"Anonymous: Rat e phone er light off kore video dekhi",
"Anonymous: Crush er sathe group photo te majhe darate chai",
"Anonymous: Friend ke boli 'taka nai' kintu biriyani khai",
"Anonymous: Online e kawke gali disi",
"Anonymous: Crush er id password guess kori",
"Anonymous: Class e sir ke jiggesh kori 'sir bujhi nai' kintu monojog chilona",
"Anonymous: Rat e ex er puran chat pori",
"Anonymous: Friend ke boli 'ami ghumabo' kintu reel dekhi",
"Anonymous: Crush ke niye kobita likhsi",
"Anonymous: Online e nijeke cool dabi kori",
"Anonymous: Exam e pasher jon er ta dekhi",
"Anonymous: Crush ke dekhe hashi pai",
"Anonymous: Rat e aka gaan gai",
"Anonymous: Friend er jonno wait kore boshe thaki",
"Anonymous: Online e kawke 'miss you' bolsi",
"Anonymous: Crush er sathe kotha bolar jonno new id khulsi",
"Anonymous: Ma ke boli 'ami pori' kintu game kheli",
"Anonymous: Exam er result dekhe kanna korsi",
"Anonymous: Crush ke 'tumi shundor' bolte chai kintu sahosh pai na",
"Anonymous: Rat e aka nijer sathe kotha boli",
"Anonymous: Friend ke boli 'ami change hoisi' kintu same asi",
"Anonymous: Online e kawke 'love you' bolsi",
"Anonymous: Crush er sathe dekha hole ki bolbo vabi",
"Anonymous: Exam e time sesh hoye jay likha sesh hoy na",
"Anonymous: Rat e phone charge e diye ghumai na",
"Anonymous: Crush er sathe chat korte giye seen kore rakhi",
"Anonymous: Friend ke boli 'tui amar bestie'",
"Anonymous: Online e nijeke sad dabi kori like er jonno",
"Anonymous: Crush ke niye friend der kase boli",
"Anonymous: Exam e syllabus sesh kori na",
"Anonymous: Rat e aka haste haste kanna ashe",
"Anonymous: Crush ke propose korar plan kori kintu kori na"
];
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
module.exports = {
config: {name: "confession", aliases: ["cf"], version: "2.0.0", author: "Sazzad", countDown: 3, role: 0, shortDescription: "100+ Anonymous Confession", category: "FUN"},
onStart: async function ({ api, event, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let conf = shuffle([...confList])[0];
return sendMsg(`📝 ANONYMOUS CONFESSION 📝\n\n${conf}`);
}
};