const factList = [
"BD te cha er dam barse kintu adda komeni",
"Bangali ra exam er ager raat e sobcheye beshi pore",
"Desh e current gele sobai mombati khuje",
"WiFi er nam Free kintu password lage",
"Student ra bole ghum dorkar, raat 3tay meme dekhe",
"Restaurant e bill ashle sobai wallet khuje",
"Online e shobai gym trainer, bastobe 1ta pushup pare na",
"Eid er taka Eid er agei sesh",
"Traffic jam e boshe manush biye thik kore",
"Mobile er charge 1% thakleo video dekhe",
"BD te brishti holei rasta nodi hoye jay",
"Uber er vara shune manush rickshaw te uthe",
"Online class e sobai 'you are on mute'",
"Doctor er serial 2 mash por, jor ekhoni",
"Market e sob kichu sale, kintu dam barse",
"Mobile storage full, delete korar kichu nai",
"Exam hall e pen nosto, borrow korar keu nai",
"CGPA lagbe na, kintu job e CGPA chay",
"Birthday te wish ashe, treat keu dey na",
"Loadshedding er notun nam 'digital break'",
"Petrol er dam barse, manush hete office jay",
"Chaileo ghum ase na, na chaile ghum ase",
"Movie dekhte giye ghumay jai, pore spoiler dekhi",
"Bus e sit faka thakleo daray thaki",
"Online e shobai freelancer, payment ase na",
"Biyer dawat e khabar kom, photo beshi",
"Chai er dokan e adda ekhon 100tk per hour",
"Student der routine: ghum, khawa, tension, repeat",
"Desh e shob kichur dam barse, salary same",
"Instagram e 100 story, like 2 ta",
"New phone kine 1 ghontay bhenge feli",
"Diet korte giye raat 12tay biriyani",
"Free wifi er jonno 2 ghonta boshe bill 500tk",
"Git push korte giye project delete",
"Dark mode e din katay dei",
"Wifi slow bole router e lathi mari",
"3 ghonta charger khuji, pore dekhi lagano",
"Wifi password bhule 2GB mb kini",
"Good night bole 4 tay ghum theke uthi",
"OMR e nam er jaygay 'pass me sir' likhi",
"Zoom e speech dite giye net problem",
"Podma setu niye kotha bolte giye traffic e pori",
"Digital Bangladesh bolte giye zoom e join korte pari na",
"Exam pichabo bolle student ra party kore",
"Online class hobe, teacher join kore na",
"Gari start dite giye battery sesh",
"GPS on kore hariye jai",
"Bug fix korte giye 10 ta bug banai",
"Laptop e game khelte motherboard urai",
"Exam er din uthi dekhi kalke chilo",
"Selfie tulte giye phone pani te feli",
"ATM e card dhukay pin bhuli",
"Hair cut korate giye tak hoye jai",
"Online shopping e 5 ta order kore 1 ta pai",
"Rastar jam e boshe manush tiktok banay",
"Rickshaw wala mama ra Uber er cheye fast",
"Restaurant e AC chara bosa jay na",
"Exam er question out hoileo keu pore na",
"Online e shobai crorepati, bastobe sobai broke",
"Mobile e 30GB net, 3 din e sesh",
"Teacher bole copy koiro na, nijei guide theke pore",
"Sobai bole taka nai, restaurant full thake",
"Current gele sobai 'current kobe ashbe' status dey",
"Health conscious ra raat e biriyani order kore",
"YouTube e shobai success, comment e 'first'",
"Eid er shopping er taka Eid er age sesh",
"Pitha banate giye kitchen e agun",
"Weather report bole brishti, akash bole na",
"Shokal 8tar class 11tay hoy, 7tay uthe boshe thaki",
"Online class e teacher er voice nai, chat e 'can you hear me'",
"Night owl ra sokale uthte giye abar raat hoy",
"Bondhu ra bole ghorte jai, pocket bole na",
"Crush ke 'bro' bole feli propose korte giye",
"Assignment 1 ta, excuse 10 ta",
"Facebook e sobai busy, messenger e seen kore na",
"Online course kine 1% o complete kori na",
"Healthy khao, kintu raat e biriyani order hoy",
"Taka save koro, kintu sale dekhle matha nosto",
"Weekend e plan 10 ta, ghum 1 ta",
"Office e boss bole kaj kom, nije 5 ta meeting dey",
"Salary ashe 1 tarikh e, sesh hoy 2 tarikh e",
"Bap ma bole phone kom chalao, nijei tiktok dekhe",
"Gym membership niye bashay boshe thaka",
"Exam sesh howar por sobai bole 'question easy chilo'",
"WiFi slow hole jibon o slow hoye jay",
"Biriyani dekhle diet er kotha mone thake na",
"Student der 3 ta season: Exam, Result, Tension",
"Crush online e active kintu reply nai",
"Result er age sobai fail dhore ney",
"Traffic jam e boshe manush biye thik kore",
"Desh e shobai doctor, shobai engineer, keu kaj kore na",
"Restaurant e khabar er dam dekhe pet bhore jay"
];
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
module.exports = {
config: {name: "fact", aliases: ["f", "bdFact"], version: "2.0.0", author: "Sazzad", countDown: 3, role: 0, shortDescription: "100+ BD Weird Fact", category: "FUN"},
onStart: async function ({ api, event, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let fact = shuffle([...factList])[0];
return sendMsg(`🤯 WEIRD BD FACT 🤯\n\n${fact}\n\n- IVORY TALKS`);
}
};