const memeList = [
"Exam ashtese: Brain - ami to ghumabo",
"Ma: Phone rakh | Ami: 5 min | 5 min = 5 ghonta",
"Crush: Hi | Ami: seen",
"Bank balance: 20tk | Mon: biriyani khabo",
"Teacher: Boi kholo | Class: ghumao",
"Monday morning = soul leave body",
"Diet shuru kalke theke, ajke last biriyani",
"Online class join korsi ghum er jonno",
"Result kharap hole bole question hard chilo",
"WiFi slow = jibon sesh",
"Exam er ager raat: Ami porbo | 3AM: Ghumai",
"Mobile: 1% charge | Ami: Arektu video dekhi",
"Crush online | Ami: typing... delete",
"Bondhu: Treat de | Pocket: 10tk",
"Sir: Homework koi | Ami: Batashe uray gese",
"Alarm: 6AM | Ami: Snooze 10 bar",
"Online e shobai gym bro | Bastobe 0 pushup",
"Eid er salami: 500tk | 2 ghontay sesh",
"Traffic jam: 2 ghonta | Manush: biye thik kore",
"Doctor: pani khao | Ami: Coca-Cola khai",
"Ma: Porashona kor | Ami: YouTube e 'how to study'",
"Crush er post: 1 sec e like",
"Exam e likhi: 'Joto tuku mone ache'",
"WiFi password: bhule gesi | MB: 2GB kinlam",
"Gym membership: 1 mash | Gelam: 1 din",
"Diet: Coke charbo | Rate: Coke + Biriyani",
"Online class: Camera off, Mic off, Brain off",
"Birthday: Wish 100 ta | Treat: 0 ta",
"Salary: 1 tarikh | Bank: 2 tarikh",
"Raat 12ta: Ghumabo | Raat 4ta: Reel dekhi",
"Crush: Bro bole dakse | Heart: bhenge gese",
"Teacher: Easy question | Ami: Etao pari na",
"Mobile storage: Full | Gallery: Meme 5000 ta",
"Exam hall: Pen sesh | Pasher jon: Ghumay",
"Weather: Brishti hobe na | 5 min por: Jolash",
"Uber: 400tk | Rickshaw: 200tk | Ami: hete jai",
"Online shopping: Pic e 1 ta | Ashlo: arekta",
"Crush er sathe kotha: 2 line | Vabi: 2 ghonta",
"Assignment: 1 din time | Ami: Last 1 ghontay",
"Ma: Rate taratari ghumabi | Ami: 3AM",
"Friend: Ghorte jai | Ami: Taka nai | Friend: Amar o nai",
"Instagram: 100 story | View: 3 ta",
"New phone: 1 week | Display: bhenge gese",
"Crush ke propose: 'Tumi valo' | Reply: 'Thanks bro'",
"Online e shobai doctor | Jor hole Google kori",
"Restaurant e menu dekhe: Pet bhore jay",
"Exam er result: Fail | Reason: Question hard",
"WiFi: Free | Speed: 2KB/s",
"Ghum: 8 ghonta dorkar | Ghumai: 4 ghonta",
"Crush er bio: 'Single' | Ami: Asha pelam",
"Teacher: Next class e exam | Class: Shok",
"Mobile: Charge e lagano | Ami: Charger khuji",
"Birthday cake: Nije kine nije khai",
"Online e shobai rich | Bastobe sobai broke",
"Exam er age: Porbo | Exam er por: Easy chilo",
"Crush: Active 2 min age | Msg: Seen nai",
"Ma: Khawa dawa kor | Ami: Diet e asi",
"Friend: Tui change hoisos | Ami: Same asi",
"Online class: 'Can you hear me sir?'",
"Traffic: 1 ghonta | Gari: 100 meter",
"Bank: Balance kom | Mon: Shopping korte chai",
"Crush er friend: O single na | Ami: Depression",
"Exam: OMR bhul | Sir: 0",
"WiFi: Full signal | Net: Cholena",
"Gym: Protein shake | Bashay: Vat dal",
"Crush: DP change korse | Ami: 10 bar dekhsi",
"Teacher: Chup koro | Class: Arektu jore kotha",
"Online: 'Ami busy' | Status: Online 6 ghonta",
"Exam: Question common | Ami: pori nai",
"Mobile: Update chaitese | Storage: nai",
"Crush: Biye thik hoye gese | Ami: RIP",
"Friend: Tui mota hoisos | Ami: Gym e jabo",
"Raat: Ghum ashe na | Din: Class e ghum",
"Online: Meme dekhi | Exam: Fail kori",
"Ma: Phone rakh | Ami: Last video",
"Crush: Hi bolse | Ami: 30 min vebe reply",
"Bank: Loan nite hobe | Mon: iPhone kinbo",
"Exam: Syllabus onek | Ami: 1 chapter",
"WiFi: Disconnect | Life: Disconnect",
"Gym: Jabo kalke theke | Kalke: kokhono ashe na",
"Crush: BF ache | Ami: Friend thaki",
"Teacher: Present | Ami: Ghumay",
"Online: Sobai success | Ami: Try kortesi",
"Exam: Copy korte giye dhora",
"Mobile: 100% | 1 ghonta por: 20%",
"Crush: Online na | Ami: Tension",
"Friend: Treat de | Ami: Next month",
"Raat: Porbo | Raat: Ghum",
"Online: 'Motivational quote' | Bastobe: Ghum",
"Exam: Hall e ghuri nai | Time: sesh",
"WiFi: Password change | Ami: Baire boshe thaki",
"Crush: Block korse | Ami: New id",
"Teacher: Homework check | Ami: Kori nai",
"Mobile: Memory full | Delete: Korte pari na",
"Online: Shobai couple | Ami: Single",
"Exam: Easy chilo | Result: F",
"Crush: Ignore kore | Ami: Aro msg dei",
"Friend: Ghumay ja | Ami: Arekta meme"
];
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
module.exports = {
config: {name: "meme", aliases: ["me", "textmeme"], version: "2.0.0", author: "Sazzad", countDown: 3, role: 0, shortDescription: "100+ Text Meme", category: "FUN"},
onStart: async function ({ api, event, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let meme = shuffle([...memeList])[0];
return sendMsg(`😂 RANDOM MEME 😂\n\n${meme}`);
}
};