const newsList = [
"protik: Exam er din ghum theke uthe dekhe exam kalke chilo",
"protik: Biriyani khete giye plate soho kheye felse",
"protik: Crush er samne pore giye bolse ami yoga kortesilam",
"protik: Free wifi er jonno 2 ghonta boshe theke bill dise 500tk",
"protik: Online class e camera on kore ghumay gese",
"ashfiq: Gym e giye selfie tule bashay chole ashe",
"ashfiq: Diet korte giye raat 12tay biriyani khay",
"ashfiq: Crush ke hi bolte giye block khaise",
"ashfiq: New phone kine 1 ghontar moddhe bhenge felse",
"ashfiq: Instagram e 100 ta story diye 2 ta like",
"Subaru: Drift korte giye gari gash e uthay dise",
"Subaru: Petrol er dam shune cycle kinse",
"Subaru: GPS on kore hariye gese",
"Subaru: Car e ghumay giye police er kase dhorha khaise",
"Subaru: Gari start dite giye battery sesh",
"ariyan: Bug fix korte giye aro 10 ta bug banay felse",
"ariyan: Git push korte giye delete kore dise",
"ariyan: AI ke jiggesh korse tumi ki amar ex?",
"ariyan: Laptop e game khelte giye motherboard uray dise",
"ariyan: StackOverflow copy kore nije senior dabi kore",
"sazzad: Sazzad elakar gorib der jonno free khabarer bebostha korlo",
"sazzad: Sazzad 10 jon student ke scholarship dilo",
"sazzad: Sazzad hospital e giye rogi der fol dilo",
"sazzad: Sazzad rastar kukur der jonno khabar dey protidin",
"sazzad: Sazzad blood diye 3 jon er jibon bachalo",
"shamim: Shamim 3 ghonta dhore charger khujte giye dekhe charge e lagano",
"shamim: Shamim 'ami busy' bole 6 ghonta pubg khelse",
"shamim: Shamim meye dekhte giye nijer chobi dekhay dise",
"shamim: Shamim exam e likhse 'sir apni pass'",
"shamim: Shamim wifi password bhule giye mb kinse 2GB",
"pranto: Pranto gym membership niye bashay boshe biriyani khay",
"pranto: Pranto crush ke propose korte giye 'bro' bole felsilo",
"pranto: Pranto rate jege reel dekhe sokale alarm off kore ghumay",
"pranto: Pranto nijer cake nije kheye bole ke khaise?",
"pranto: Pranto online e juta order kore slipper paise",
"siam: Siam 2 ghonta dhore khujteche chosma, pore ache mathay",
"siam: Siam girlfriend ke 'good night' bole 4 ta baje ghum theke uthse",
"siam: Siam biriyani order diye rice khawa shuru korse",
"siam: Siam exam e omr e nam er jaygay 'pass me sir' likhse",
"siam: Siam tiktok e viral hoite giye 3 ta view paise",
"sheikh hasina: Sheikh Hasina desh er unnoyon niye bhashon dite giye current chole gese",
"sheikh hasina: Sheikh Hasina digital Bangladesh er kotha bolte giye zoom e join korte pare nai",
"sheikh hasina: Sheikh Hasina podma setu niye kotha bolte giye traffic jam e porse",
"modi: Modi chai bechte bechte PM hoye gelo ekhon abar chai er dam barse",
"modi: Modi Twitter e 'Mann Ki Baat' korte giye nijer tweet e nijei like dise",
"modi: Modi yoga day te yoga korte giye komor betha paise",
"tarek zia: Tarek Zia London theke zoom e speech dite giye net problem",
"tarek zia: Tarek Zia 'ami ashtesi' bole 15 bochor par",
"tarek zia: Tarek Zia BNP office e giye daroan ke jiggesh korse meeting koi?",
"khawwa kader: Khawwa Kader press conference korte giye nijei press hoye gese",
"khawwa kader: Khawwa Kader sara raat ghumay na, shokal e ghumay",
"khawwa kader: Khawwa Kader mic er samne ese bole 'ami ki bolbo?'",
"milon: Shikkha Montri Milon bollo exam pichabe, student ra party shuru korlo",
"milon: Milon bollo boi poro, nije facebook e meme dekhe",
"milon: Milon syllabus komay dise, prosno aro kothin korse",
"milon: Milon bollo online class hobe, teacher nijei join kore nai",
"milon: Milon result er din bollo tension nio na, pore tension baray dilo",
"ronaldo: Ronaldo gym e 5 ghonta, tarpor o bollo aro workout dorkar",
"ronaldo: Ronaldo SIUUU korte giye gola betha paise",
"ronaldo: Ronaldo match er por abar training e chole gese",
"messi: Messi ghum theke uthe 3 ta goal diye abar ghumay gese",
"messi: Messi World Cup er trophy niye ghore sajay rakhse",
"messi: Messi Inter Miami te giye o GOAT thaklo",
"mbappe: Mbappe speed e dourate giye nijei hariye gese",
"mbappe: Mbappe Real Madrid e giye jersey number khujteche",
"mbappe: Mbappe hat-trick kore bollo 'normal day'",
"neymar: Neymar skill korte giye nijei pore gese",
"neymar: Neymar party kore porer din match e hat-trick",
"neymar: Neymar bole 'football hocche moja'",
"vini jr: Vini Jr dribbling korte giye 5 jon ke katay felse",
"vini jr: Vini Jr racism er biruddhe kotha bole sobar mon jitlo",
"vini jr: Vini Jr match e dance kore goal celebrate korlo",
"elon musk: Elon Musk Twitter kine nam dilo X, ekhon abar X kuje",
"elon musk: Elon Musk Mars e jabe bole ticket er dam baray dise",
"elon musk: Elon Musk AI banay bollo 'eta amake control korbe'",
"mrbeast: MrBeast 1 million dollar diye bollo 'last to leave'",
"mrbeast: MrBeast chocolate banay sobai ke free te dilo",
"mrbeast: MrBeast video banate giye island kine fello",
"bd football: BD Football team practice kortese, goal net chilo na",
"bd football: BD Footballer ra bollo amra o world cup khelbo",
"bd football: BD Football league e referee nijei goal dilo",
"bd football: BD Football fan ra stadium e giye dekhe gate off",
"cricket: Bangladesh cricket team practice e 6 marlo, ball ar pawa gelo na",
"cricket: Shakib bollo ami all-rounder, sobai bollo hae",
"cricket: Cricket match e DRS niye 10 min torko",
"cricket: Bowler no ball dilo, umpire o kheyal kore nai",
"cricket: Fan ra stadium e boshe brishtir doa kortese",
"Breaking: Desh e dim er dam barse, murgi ra ekhon VIP",
"Breaking: Gorom e AC kinte giye dekhi current nai",
"Breaking: Student ra bollo porashona komay dao, Montri bollo ghum komay dao",
"Breaking: Petrol er dam shune manush ekhon hete hete office jay",
"Breaking: Facebook e sobai rich, bastobe sobai broke",
"Breaking: Online e job khujte giye 500 ta scam er offer paise",
"Breaking: Exam er age raat jege porle brain bole 'kalke mone koray dimu'",
"Breaking: Desh e internet slow, kintu bill fast",
"Breaking: Restaurant e khabar er dam dekhe pet bhore jay",
"Breaking: Bondhu ra bollo treat de, ami bollam gorib",
"Breaking: Mosquito ra ekhon AC room e thake",
"Breaking: Loadshedding er notun nam 'digital break'",
"Breaking: Teacher ra bole phone kom chalao, nijei class e reel dekhe",
"Breaking: Bazar korte giye dekhi taka diyeo shanti nai",
"Breaking: Rain ashle rickshaw wala ra business man hoye jay",
"Breaking: YouTube e sobai crorepati, comment e sobai 'first'",
"Breaking: Exam hall e ghori niye jawa baron, kintu time dekhar jonno ghori lage",
"Breaking: Desh e shob kichur dam barse, shudhu salary same",
"Breaking: Night owl ra sokale uthte giye abar raat hoye jay",
"Breaking: Chai er dokan e adda ekhon 100tk per hour",
"Breaking: Student der notun routine: ghum, khawa, tension, repeat",
"Breaking: Biyer dawat e khabar kom, photo beshi",
"Breaking: Traffic jam e boshe manush ekhon gaan er album banay",
"Breaking: Online e course kine 1% o complete kore nai",
"Breaking: Desh e shobai doctor, shobai engineer, keu kaj kore na",
"Breaking: Eid er por shopping er taka, Eid er agei sesh",
"Breaking: Mobile er charge 1% thakleo manush video dekhe",
"Breaking: Pitha banate giye kitchen e agun lagse",
"Breaking: Weather report bole brishti hobe, akash bole na",
"Breaking: Gym e vorti hoye weight barse, karon protein shake e chini beshi",
"Breaking: Shokal 8tar class 11tay hoy, student ra 7tay uthe boshe thake",
"Breaking: Desh e cha er dam barse, adda ekhon 30min er",
"Breaking: Exam er question out hoise, kintu keu pore nai",
"Breaking: WiFi er nam 'FreeNet' kintu password lage",
"Breaking: Student ra bole assignment kom dao, sir dise aro 3ta",
"Breaking: Uber vara shune manush rickshaw te uthe",
"Breaking: Biriyani er dam 300tk, taste 100tk er",
"Breaking: Desh e gorom barse, fan er batas o gorom",
"Breaking: Office e boss bole kaj kom, nije 5ta meeting dey",
"Breaking: Student ra porikkhay likhe 'joto tuku mone ache'",
"Breaking: Market e gele dekhi sob kichu 'sale' kintu dam barse",
"Breaking: Rat 12tar por net speed bare, ghum ashe na",
"Breaking: Crush online e active kintu reply dey na",
"Breaking: Desh e shobai content creator, keu content dekhe na",
"Breaking: Exam er 1 din age syllabus sesh hoy",
"Breaking: Bap ma bole phone kom chalao, nijei tiktok dekhe",
"Breaking: Bus e sit faka thakleo daray jay",
"Breaking: Online class e teacher er voice ase na, chat e 'can you hear me'",
"Breaking: Shobai bole taka nai, kintu restaurant full",
"Breaking: Desh e current gele sobai mombati khuje",
"Breaking: Student ra bole ghum dorkar, raat 3tay meme dekhe",
"Breaking: Doctor er appointment 2 mash por, jor ekhoni",
"Breaking: Chaileo ghum ase na, na chaile ghum ase",
"Breaking: Exam er por sobai bole 'question easy chilo'",
"Breaking: Desh e traffic er jam e manush biye thik kore",
"Breaking: Mobile er storage full, kintu delete korar moto kichu nai",
"Breaking: Online e shobai gym trainer, bastobe 1ta pushup pare na",
"Breaking: Restaurant e bill ashle sobai wallet khuje",
"Breaking: Student ra bole practical easy, number kom pay",
"Breaking: Desh e shobai critic, keu kaj kore na",
"Breaking: Birthday te wish ashe kintu treat keu dey na",
"Breaking: Rat e ghum ashe na, din e class e ghum ashe",
"Breaking: Shobai bole savings koro, salary sesh 10 tarikh e",
"Breaking: Exam hall e pen nosto, borrow korar o keu nai",
"Breaking: Desh e brishti holei rasta nodi hoye jay",
"Breaking: Online e meeting e sobai 'you are on mute'",
"Breaking: Student ra bole CGPA lagbe na, job er jonno CGPA chay",
"Breaking: Cha er sathe biscuit 20tk, biscuit chara 15tk",
"Breaking: Desh e shobai freelancer, payment ase na",
"Breaking: Movie dekhte giye ghumay jay, pore spoiler dekhe",
"Breaking: Exam er result er agei sobai fail dhore ney",
"Breaking: Desh e internet package 30GB, 3 din e sesh",
"Breaking: Shobai bole healthy khao, raat e biriyani order hoy",
"Breaking: Teacher bole copy koiro na, nijei guide theke pore"
];
function shuffle(array) {
for (let i = array.length - 1; i > 0; i--) {
const j = Math.floor(Math.random() * (i + 1));
[array[i], array[j]] = [array[j], array[i]];
}
return array;
}
module.exports = {
config: {
name: "news",
aliases: ["n"],
version: "3.1.0",
author: "Sazzad",
countDown: 5,
role: 0,
shortDescription: "200+ Funny News",
category: "FUN"
},
onStart: async function ({ api, event, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let usedNames = new Set();
let selected = [];
for(let item of shuffle([...newsList])){
let name = item.split(": ")[0];
if(!usedNames.has(name) && selected.length < 6){
usedNames.add(name);
selected.push(item);
}
}
let msg = "🚨 BREAKING NEWS 🚨\n\n";
selected.forEach((news, i) => {
let [name, content] = news.split(": ");
let tag = name == "Breaking"? "TAZA NEWS" : name.toUpperCase();
msg += `${i+1}. ${tag}: ${content}\n\n`;
});
msg += "━━━━━━━━━━━━━━━\n";
msg += "📺 Channel: IVORY TALKS NEWS BD\n";
msg += "🕒 Update: Just Now";
return sendMsg(msg);
}
};