const quoteList = [
"Life e 2 ta jinish impossible: 1. Ghum theke utha 2. Diet kora",
"Exam er ager raat = brain er full charge",
"Taka thakle sobai dostho, na thakle phone busy",
"Crush reply na dile bujhte hobe tumi free wifi na",
"Ghum kom porashona beshi = result e bash",
"Success er shortcut nai, kintu biriyani ache",
"Bondhu ra bole treat de, pocket bole gorib",
"Online class e camera off = attendance on",
"Rat 12tar por sobai motivational speaker",
"Monday mane notun kore tension shuru",
"Exam sesh howar por sobai bole 'question easy chilo'",
"WiFi slow hole jibon o slow hoye jay",
"Biriyani dekhle diet er kotha mone thake na",
"Mobile er charge 1% thakleo video chere na",
"Student der 3 ta season: Exam, Result, Tension",
"Salary ashe 1 tarikh e, sesh hoy 2 tarikh e",
"Crush online e active kintu reply nai",
"Bap ma bole phone kom chalao, nijei tiktok dekhe",
"Gym membership niye bashay boshe thaka",
"Online e shobai crorepati, bastobe sobai broke",
"Cha er dam barse, kintu adda kome nai",
"Exam er question out hoise, kintu keu pore nai",
"Raat e ghum ase na, din e class e ghum ashe",
"Doctor er appointment 2 mash por, jor ekhoni",
"Uber er vara shune manush rickshaw te uthe",
"Assignment 1 ta, excuse 10 ta",
"Facebook e sobai busy, messenger e seen kore na",
"Result er age sobai fail dhore ney",
"Online course kine 1% o complete kori na",
"Traffic jam e boshe manush biye thik kore",
"Mobile storage full, delete korar kichu nai",
"Exam hall e pen nosto, borrow korar keu nai",
"Desh e brishti holei rasta nodi hoye jay",
"Meeting e sobai 'you are on mute'",
"CGPA lagbe na, kintu job e CGPA chay",
"Healthy khao, kintu raat e biriyani order hoy",
"Teacher bole copy koiro na, nijei guide theke pore",
"Taka save koro, kintu sale dekhle matha nosto",
"Weekend e plan 10 ta, ghum 1 ta",
"Birthday te wish ashe, treat keu dey na",
"Loadshedding er notun nam 'digital break'",
"Petrol er dam barse, manush hete office jay",
"Student ra bole ghum dorkar, raat 3tay reel dekhe",
"Office e boss bole kaj kom, nije 5 ta meeting dey",
"Market e gele sob kichu sale, kintu dam barse",
"Online e shobai gym trainer, 1 ta pushup pare na",
"Restaurant e khabar er dam dekhe pet bhore jay",
"YouTube e shobai success, comment e 'first'",
"Desh e shobai doctor, shobai engineer, keu kaj kore na",
"Eid er shopping er taka Eid er age sesh",
"Pitha banate giye kitchen e agun",
"Weather report bole brishti, akash bole na",
"Gym e vorti hoye weight barse, protein e chini beshi",
"Shokal 8tar class 11tay hoy, 7tay uthe boshe thaki",
"Uber na pele rickshaw wala ra business man",
"Online class e teacher er voice nai, chat e 'can you hear me'",
"Sobai bole taka nai, restaurant full thake",
"Current gele sobai mombati khuje",
"Chaileo ghum ase na, na chaile ghum ase",
"Mobile e 30GB net, 3 din e sesh",
"Movie dekhte giye ghumay jai, pore spoiler dekhi",
"Exam er 1 din age syllabus sesh hoy",
"Bus e sit faka thakleo daray thaki",
"Crush ke 'bro' bole feli propose korte giye",
"Online e shobai freelancer, payment ase na",
"Biyer dawat e khabar kom, photo beshi",
"Night owl ra sokale uthte giye abar raat hoy",
"Chai er dokan e adda ekhon 100tk per hour",
"Student der routine: ghum, khawa, tension, repeat",
"Desh e shob kichur dam barse, salary same",
"Exam e likhi 'joto tuku mone ache'",
"Bondhu ra bole ghorte jai, pocket bole na",
"Instagram e 100 story, like 2 ta",
"New phone kine 1 ghontay bhenge feli",
"Diet korte giye raat 12tay biriyani",
"Crush ke hi bolte giye block khai",
"Free wifi er jonno 2 ghonta boshe bill 500tk",
"Online class e camera on kore ghumay jai",
"Git push korte giye project delete",
"AI ke jiggesh kori tumi ki amar ex?",
"StackOverflow copy kore senior dabi kori",
"Dark mode e din katay dei",
"Wifi slow bole router e lathi mari",
"Blood diye 3 jon er jibon bachai, credit nei na",
"Rastar kukur der jonno protidin khabar dei",
"Hospital e giye rogi der fol dei",
"10 jon student ke scholarship dei",
"Elakar gorib der jonno free khabar",
"3 ghonta charger khuji, pore dekhi lagano",
"'Ami busy' bole 6 ghonta pubg",
"Meye dekhte giye nijer chobi dekhai",
"Exam e likhi 'sir apni pass'",
"Wifi password bhule 2GB mb kini",
"Gym membership niye biriyani khai",
"Rate jege reel dekhi, sokale alarm off kore ghumai",
"Nijer cake nije kheye boli ke khaise?",
"Online e juta order kore slipper pai",
"2 ghonta chosma khuji, mathay thake",
"Good night bole 4 tay ghum theke uthi",
"Biriyani order diye sudhu rice khai",
"OMR e nam er jaygay 'pass me sir' likhi",
"Tiktok e viral hote giye 3 view",
"Press conference e boli 'ami ki bolbo?'",
"Sara raat ghumai na, shokal e ghumai",
"Zoom e speech dite giye net problem",
"'Ami ashtesi' bole 15 bochor par",
"BNP office e giye jiggesh kori meeting koi?",
"Digital Bangladesh bolte giye zoom e join korte pari na",
"Podma setu niye kotha bolte giye traffic e pori",
"Chai bechte bechte PM, ekhon chai er dam barse",
"Mann Ki Baat korte giye nijei like dei",
"Yoga day te yoga kore komor betha",
"Syllabus komay prosno kothin kori",
"Boi porte boli, nije meme dekhi",
"Exam pichabo bolle student ra party kore",
"Online class hobe, teacher join kore na",
"Result er din boli tension nio na",
"Gari start dite giye battery sesh",
"Drift korte giye gash e uthi",
"GPS on kore hariye jai",
"Car e ghumay police er kase dhora",
"Petrol er dam shune cycle kini",
"Bug fix korte giye 10 ta bug banai",
"Laptop e game khelte motherboard urai",
"Exam er din uthi dekhi kalke chilo",
"Plate soho biriyani khai",
"Crush er samne pore boli yoga kortesi",
"Selfie tulte giye phone pani te feli",
"ATM e card dhukay pin bhuli",
"Hair cut korate giye tak hoye jai",
"Online shopping e 5 ta order kore 1 ta pai",
"Instagram e 100 story diye 2 like",
"Last to leave khelar jonno 1 million urai",
"Chocolate banay sobai ke free dei",
"Video banate giye island kini",
"Twitter kine nam dei X, ekhon X khuji",
"Mars e jabo bole ticket er dam barai",
"AI banay boli eta amake control korbe",
"SIUUU korte giye gola betha",
"Match er por abar training",
"Ghume theke uthe 3 goal diye abar ghumai",
"World Cup trophy ghore sajai",
"Inter Miami te giye o GOAT thaki",
"Speed e dourate giye nije hariye jai",
"Real Madrid e giye jersey number khuji",
"Hat-trick kore boli normal day",
"Skill korte giye nije pore jai",
"Party kore porer din hat-trick",
"Football hocche moja",
"Dribbling korte 5 jon ke katay feli",
"Racism er biruddhe kotha boli",
"Dance kore goal celebrate kori",
"BD team practice kore, net nai",
"BD player ra bole world cup khelbo",
"BD league e referee nije goal dei",
"BD fan ra stadium e giye dekhe gate off",
"Bangladesh 6 marlo, ball ar pawa gelo na",
"Shakib bole ami all-rounder",
"DRS niye 10 min torko",
"Bowler no ball dilo, umpire kheyal korlo na",
"Fan ra brishtir doa kore stadium e"
];
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
module.exports = {
config: {name: "quote", aliases: ["q"], version: "2.0.0", author: "Sazzad", countDown: 3, role: 0, shortDescription: "200+ Funny Quote", category: "FUN"},
onStart: async function ({ api, event, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let quote = shuffle([...quoteList])[0];
return sendMsg(`💬 QUOTE OF THE DAY 💬\n\n"${quote}"\n\n- IVORY TALKS`);
}
};