const truthList = [
"Last kake crush korsila?",
"Phone e koto % charge ache?",
"Last karaoke te ki gaisila?",
"Ex er nam ki?",
"Crush ke kokhono text korsila?",
"Life er sobcheye boro mittha ki bolsila?",
"Koyta relationship korsila?",
"Last kobe kanna korsila?",
"Phone er gallery te sobcheye embarrassing pic konta?",
"Kawke secret crush koro?",
"Last kake stalk korsila?",
"Room e aka thakle ki koro?",
"Karo upor rag kore block korsila?",
"Exam e kokhono nokol korsila?",
"Ma er kase mittha bole kothay gesila?",
"Friend er khabar churi kore khaisila?",
"Rate ghum ashe na keno?",
"Crush er reply na pele ki koro?",
"Last kobe jhogra korsila?",
"Phone er password ki?",
"Bank e koto taka ache?",
"Kawke posondo kore bolo nai?",
"School e sir er kase dhora khaisila?",
"Instagram e fake id ache?",
"Tiktok e nijer video upload korsila?",
"Last kobe online e kandisila?",
"Karo DM e cringe msg disila?",
"Life er sobcheye boro regret ki?",
"Crush er samne lojja paisila?",
"Kawke propose korte giye reject khaisila?",
"Last kobe ghumao nai?",
"Porashona na kore ki koro?",
"Karo pasword jano?",
"Phone e koto ta gf/bf er chat ache?",
"Last kobe movie dekhso?",
"Gan geye paro?",
"Rate 3tay ki koro?",
"Kawke niye sopno dekhso?",
"Friend er pechone kotha bolsila?",
"Selfie koto gula tulo dine?",
"Crush er story sob dekho?",
"Last kobe treat disila?",
"Taka poysha niye mittha bolsila?",
"Kawke jealous korso?",
"Ex ke ekhono mone pore?",
"Life e sobcheye lojjar muhurto ki?",
"Online e nijeke rich dabi korso?",
"Gym e giye sudhu selfie tulo?",
"Diet korte giye dhoka diso?",
"Assignment copy korsila?",
"Teacher er nam e nickname ki?",
"Class e ghumaisila?",
"Crush er friend ke jiggesh korsila?",
"Last kobe brishti te vijsila?",
"Kawke ignore korsila?",
"Phone e koto ghonta time nosto koro?",
"Last kobe haste haste kanna ashsilo?",
"Karo jonno wait korsila?",
"Life e sobcheye boro vul ki?",
"Kawke sorry bolo nai kintu dosh chilo?",
"Rat e ki dekho phone e?",
"Crush er post e first like deo?",
"Kawke niye golpo banaisila?",
"Last kobe rag kore jinish bhangso?",
"Family er kase lukano secret ki?",
"Online e kawke flirt korsila?",
"Exam er age raat jege ki koro?",
"Crush er sathe kotha bolte voy pao?",
"Last kobe nijeke niye gorbo korsila?",
"Kawke choto korsila?",
"Friend er sathe jhogra kore kotha bondho?",
"Phone e koto ta app ache?",
"Last kobe kauke gift disila?",
"Kawke mone mone gaali disila?",
"Life e sobcheye khushir din konta?",
"Crush er sathe dekha hole ki bolba?",
"Kawke stalk kore dhora khaisila?",
"Rat e ghum er age ki chinta koro?",
"Last kobe mittha kotha dhora khaisila?",
"Kawke posondo kore nam change korsila?",
"Exam e 'pass me sir' likhsila?",
"Crush er sathe chat delete korso?",
"Life e sobcheye boro shopno ki?",
"Kawke niye kawke bolsila?",
"Last kobe nijer upor rag hoisilo?",
"Phone e cringe video ache?",
"Crush ke dekhle heart beat bare?",
"Kawke jealousy te msg disila?",
"Last kobe kawke hug korsila?",
"Life e sobcheye koster din konta?",
"Crush er sathe selfie ache?",
"Kawke niye status disila?",
"Last kobe rat jege porso?",
"Friend er secret fash korsila?",
"Crush er sathe kotha bolar bahana?",
"Life e sobcheye boro achievement ki?",
"Kawke propose korar plan ache?",
"Last kobe kawke miss korsila?",
"Phone e ex er pic ache?",
"Crush er sathe dream e dekha hoise?",
"Kawke niye kobita likhsila?",
"Last kobe nije ke niye hashsila?",
"Life e abar ki korte chao?",
"Crush jodi samne ashe ki korba?",
"Kawke block kore abar unblock?",
"Last kobe nije ke change korte chaisila?"
];

const dareList = [
"Group e 'ami gorib' likhe post dao",
"5 ta pushup dao",
"Crush ke hi bolo",
"Voice e gaan gao",
"Profile pic change koro ekhon",
"Status dao 'ami single'",
"Last photo ta group e dao",
"Crush er puran post e comment koro",
"Ma ke call diye 'I love you' bolo",
"Friend ke voice msg e gaan gao",
"10 bar 'ami bokachoda' likho",
"Ekta funny dance er video dao",
"Crush ke 'tumi shundor' bolo",
"Group admin ke 'tumi best' bolo",
"Ekta meme share koro",
"Online e 'treat chai' status dao",
"Crush er dp te react dao",
"Ekta tongue twister bolo voice e",
"Ekta golpo banay 2 line likho",
"Amake roast koro",
"Nickname change koro 1 din er jonno",
"Ekta selfie tule group e dao",
"Crush ke call dao",
"Ekta riddle bolo",
"Ekta shayari bolo",
"Friend ke gali dao moja kore",
"Ekta tiktok trend koro",
"Profile bio te 'single and available' dao",
"Crush er sathe screenshot dao",
"Ekta challenge nao",
"5 ta situp dao",
"Ekta joke bolo",
"Amake bhai bolo 10 bar",
"Crush ke sticker pathao",
"Ekta drawing tule dao",
"Ekta voice note e hasho",
"Group e 'ami ghumai' likhe ghumay jao",
"Crush er puran msg khujo",
"Ekta English sentence bolo",
"Ekta Bangla kobita bolo",
"Friend ke 'tumi amar bestie' bolo",
"Ekta funny face er pic dao",
"Crush ke friend request pathao",
"Ekta truth bolo group e",
"Ekta dare nije nije nao",
"Amake 'sir' bole dakho",
"Ekta emoji diye moner obostha bujhao",
"Crush er nam 3 bar likho",
"Ekta song er line gao",
"Group e 'ami kanna kortesi' likho",
"Ekta prank koro karo sathe",
"Crush ke 'kemon aso' jiggesh koro",
"Ekta math koro",
"Ekta spelling bolo",
"Amake roast korar reason bolo",
"Crush er sathe 5 min kotha bolo",
"Ekta poem likho",
"Group e 'ami pagol' likho",
"Ekta challenge complete koro",
"Crush ke 'miss you' bolo",
"Ekta truth dare khelte chao?",
"Amake 'boss' bolo",
"Ekta dance step dekhao",
"Crush ke 'tumi amar crush' bolo",
"Ekta funny video pathao",
"Group e 'treat kobe diba' bolo",
"Crush er sathe call e 1 min kotha",
"Ekta dare nijer jonno banay dao",
"Amake 'darling' bolo",
"Ekta voice e 'I love pizza' bolo",
"Crush ke 'tumi shera' bolo",
"Ekta photo edit kore dao",
"Group e 'ami online asi' likho",
"Crush ke 'reply dao' bolo",
"Ekta funny sound koro",
"Amake 'genius' bolo",
"Crush ke 'tumi cute' bolo",
"Ekta riddle er answer dao",
"Group e 'ami aka' likho",
"Crush ke 'chat kori?' bolo",
"Ekta song recommend koro",
"Amake 'legend' bolo",
"Crush ke 'tumi special' bolo",
"Ekta dance video dao",
"Group e 'ami bore' likho",
"Crush ke 'kotha bolo' bolo",
"Ekta truth bolo nijer somporke",
"Amake 'king' bolo",
"Crush ke 'tumi shundori' bolo",
"Ekta funny gif pathao",
"Group e 'ami ghumabo' likho",
"Crush ke 'online aso?' bolo",
"Ekta dare complete koro ekhon",
"Amake 'sir ji' bolo",
"Crush ke 'tumi amar favorite' bolo"
];

function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
module.exports = {
config: {name: "truthdare", aliases: ["td"], version: "2.0.0", author: "Sazzad", countDown: 3, role: 0, shortDescription: "Truth or Dare 100+", category: "FUN"},
onStart: async function ({ api, event, args, message }) {
const sendMsg = (txt) => message && typeof message.reply === "function"? message.reply(txt) : api.sendMessage(txt, event.threadID, event.messageID);
let type = args[0];
if(!type) return sendMsg("Use: #td truth or #td dare");
if(type.toLowerCase() == "truth") return sendMsg(`❓ TRUTH ❓\n\n${shuffle([...truthList])[0]}`);
if(type.toLowerCase() == "dare") return sendMsg(`⚡ DARE ⚡\n\n${shuffle([...dareList])[0]}`);
return sendMsg("truth or dare bolo bhai");
}
};